# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - auth-service
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:4001

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - auth-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=authdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AUTH_SERVICE_URL=http://auth-service:4001

  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=authdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_key

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: