apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: microservices-auth-app-auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4001
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: JWT_SECRET
          value: your_jwt_secret_key
